name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the backend image
      run: docker build ./backend --file backend/Dockerfile --target build --tag cotton-backend:ci
    - name: Build the frontend image
      run: docker build ./frontend --file frontend/Dockerfile --target build --tag cotton-frontend:ci
